# Docker Compose alternative for testing the stack
# This can be used to test the stack before deploying with NixOS
version: '3.8'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=UTC
      - PLEX_CLAIM=
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - ./media:/data:ro
    networks:
      - arr-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./data/sonarr/config:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    networks:
      - arr-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./data/radarr/config:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    networks:
      - arr-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./data/prowlarr/config:/config
    networks:
      - arr-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

networks:
  arr-network:
    driver: bridge

volumes:
  plex-config:
  sonarr-config:
  radarr-config:
  prowlarr-config:
